on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: puerco/generate-vex@04918bdd83417355d9f9e929774e3a42fbee6307
        with:
            product: pkg:generic/hello@${{ env.RELEASE_VERSION }}

