on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: puerco/generate-vex@4425ec6b2cc1ffbb6fd48d505a173adfeae21079
        with:
            product: pkg:generic/hello@${{ env.RELEASE_VERSION }}

