on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: puerco/generate-vex@8387f56f67f645f961f4e7cd4cce9861f372a15f
        with:
            product: pkg:generic/hello@${{ env.RELEASE_VERSION }}

