on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: puerco/generate-vex@222caf919e8556c13143ff2612dfbc050df2bee4
        with:
            product: pkg:generic/hello@${{ env.RELEASE_VERSION }}

